name: CI
on:
  pull_request:
  push:
    branches: [ main ]

  
jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
      - name: build ci-test
        run: |
          ./build.sh